project_name: portal
env:
  - CGO_ENABLED=1
  - GO111MODULE=on
builds:
  - binary: portal-{{ .Os }}-{{ .Arch }}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ldflags: -s -w
    targets:
      - env: GOOS=linux GOARCH=amd64
        steps:
          - run: go build -v -ldflags="-s -w" -o ./build/linux/amd64/portal
      - env: GOOS=linux GOARCH=arm64
        steps:
          - run: go build -v -ldflags="-s -w" -o ./build/linux/arm64/portal
      - env: GOOS=darwin GOARCH=amd64
        steps:
          - run: go build -v -ldflags="-s -w" -o ./build/darwin/amd64/portal
      - env: GOOS=windows GOARCH=amd64
        steps:
          - run: go build -v -ldflags="-s -w" -o ./build/windows/amd64/portal.exe
      - env: GOOS=windows GOARCH=arm64
        steps:
          - run: go build -v -ldflags="-s -w" -o ./build/windows/arm64/portal.exe
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
release:
  github:
    owner: RawBytes Inc.
    name: portal
    assets:
      - 'build/**'
