name: Create Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: 'write'

env:
  APP_NAME: "portal"
  TAG: "v0.0.1"

jobs:

  build-releases:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu]
    #     build-os: [windows,linux]
    #     arch: [amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.TAG }}
          tag_exists_error: false
          force_push_tag: false 
          message: "Latest release"

      - name: Fetch Tags
        run: git fetch --force --tags

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          cache: true
          
      - name: Setup Nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install Wails with dependencies
        run: |
            sudo apt-get update -yq && \
            sudo apt-get install -yq nsis pkg-config libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev libgtk-3-dev software-properties-common build-essential wget && \
            go install github.com/wailsapp/wails/v2/cmd/wails@latest
          
      - name: Create Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}
