name: Create Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: 'write'

env:
  APP_NAME: "portal"
  TAG: "v0.0.1"

jobs:

  build-releases:
    runs-on: [self-hosted]
    strategy:
      matrix:
        os: [ubuntu]
        # build-os: [windows,linux]
        # arch: [amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: git fetch --force --tags

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
          
      - name: Setup Nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
#       - name: Install Wails with dependencies
#         run: |
#             sudo apt-get update -yq && \
#             sudo apt-get install -yq mono-complete nsis pkg-config libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev libgtk-3-dev software-properties-common build-essential wget && \
#             go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails 
        run: |
          GOOS=linux GOARCH=amd64 wails build -f -clean -o ${{ env.APP_NAME }}-linux-amd64.exe
          GOOS=windows GOARCH=amd64 wails build -f -nsis -clean -o ${{ env.APP_NAME }}-windows-amd64.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            This is the release body.
            It can contain multiple lines of text.
          draft: false
          prerelease: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}-linux-amd64.exe
          path: ./build/bin/${{ env.APP_NAME }}-linux-amd64.exe

      - name: Upload Artifact Windows
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}-windows-amd64.exe
          path: ./build/bin/${{ env.APP_NAME }}-windows-amd64.exe
