name: Create Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: 'read'

env:
  APP_NAME: "portal"
  TAG: "v0.0.1"

jobs:

  build-releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: git fetch --force --tags

      - name: Setup paths and env 
        run: |
          mkdir -p $HOME/.local/bin
          mkdir -p $HOME/.local/lib/pkgconfig
          echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
          
      - name: Setup Nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install Wails with dependencies
        run: |
            sudo apt-get update -yq && \
            sudo apt-get install -yq nsis pkg-config libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev libgtk-3-dev software-properties-common build-essential wget && \
            go install github.com/wailsapp/wails/v2/cmd/wails@latest && \
            wget https://download.visualstudio.microsoft.com/download/pr/7c62b503-4ede-4ff2-bc38-50f250a86d89/3b5e9db04cbe0169e852cb050a0dffce/dotnet-sdk-6.0.300-linux-amd64.tar.gz && \
            wget https://download.visualstudio.microsoft.com/download/pr/8ba7087e-4513-41e5-8359-a4bcd2a3661f/e6828f0d8cf1ecc63074c9ff57685e27/aspnetcore-runtime-6.0.5-linux-amd64.tar.gz && \
            tar zxf dotnet-sdk-6.0.300-linux-amd64.tar.gz -C $HOME/dotnet-amd64 && \
            tar zxf aspnetcore-runtime-6.0.5-linux-amd64.tar.gz -C $HOME/dotnet-amd64 && \
            export DOTNET_ROOT=$HOME/dotnet-amd64 && \
            export PATH=$PATH:$HOME/dotnet-amd64

      - name: Build binaries for ${{ env.APP_NAME }}
        if: matrix.os != 'windows'
        run: |
          wails doctor
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} wails build
          mv ./build/${{ matrix.os }}/${{ matrix.arch }}/${{ env.APP_NAME }} ./build/${{ matrix.os }}/${{ matrix.arch }}/${{ env.APP_NAME }}-${{ matrix.os }}-${{ matrix.arch }}

      - name: Create nsis installer
        if: matrix.os == 'windows'
        run: |
          sudo apt-get install nsis -yq && \
          env GOOS="windows" GOARCH="amd64" wails build -nsis 

      - name: Create Release using GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: false
          name: Release ${{ github.ref }}
          args: release --clean
          config: .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ env.TAG }}
      #     release_name: Release ${{ env.TAG }}
      #     body: |
      #       This is the release notes for version ${{ env.TAG }}
      #     draft: true
      #     #prerelease: false
